# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-28 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published',
        ),
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
