# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-28 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
