# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-29 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_rental_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='active',
        ),
        migrations.AddField(
            model_name='rental',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
